--controls the roots movement 
--saves the users selection for Left Right Up Down (dpad)
--detects if crank is being used, allows movement forward
--creates a new image of the root once its moved into a new grid space